# Generated by Django 4.2.16 on 2024-11-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_incomecategory_user_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='type',
            new_name='expense_type',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='user',
        ),
    ]
